import Microphone from '../../images/microphone.jpg'
import Basketball from '../../images/basketball.jpg'
import MagnifyingGlass from '../../images/magnifyingGlass.jpg'

import {Text, NewLine} from '../../components/InfoSection/InfoSectionElems'

export const sectionData = [
  {
    img: Microphone,
    title: "Podcasts",
  },
  {
    title: "Rejecting Fred VanVleet",
    img: Basketball,
    description: <><Text>The episode follows the life of Fred VanVleet, and how he went from an underestimated student to an NBA player. The episode hooked me by stating “Its hard to sit in a room with 150 people and not get picked”. This statement seems to be false. Additionally, the episode uses mysterious music to grab the listener’s attention and states the NBA player’s name (Fred VanVleet).</Text><NewLine></NewLine><Text>This podcast is structured like a story, as it mainly focuses on Fred VanVleet’s life. The rising action starts when Fred VanVleet starts playing basketball, the climax is when Fred VanVleet can only get offers into the D-league, and the falling action occurs after the interview where he gets a position on the Toronto Raptors. The storyteller built suspense up to the slimax by showing all the work Fred VanVleet has put into his basketball career and the lengths that his parents will go to support him.</Text><NewLine></NewLine><Text>An example of masterful storytelling was when the narrator was describing Rockford. The narrator creates suspense by using pathos and describing the drugs and gang fights that occur in the area, instead of just saying ‘Rockford is a crime infested area’. I learned that even minor facts can be used to create suspense if it is told in the right way.</Text><NewLine></NewLine><Text>Some music and sound effects are used in the episode. For example, some sound effects are when the basketball goes through the hoop, making the moment feel more realistic. Some examples of music is when some mysterious, inspiring music plays at the start when we are introduced to Fred VanVleet’s life. After that, when Fred VanVleet starts to start his basketball career, faster music plays, to signify a change in pace.</Text><NewLine></NewLine><Text>On the podcast’s website, the title of the podcast is presented with a hand pushing the words “We Regret to Inform You”, with the hand representing rejection. I notice that the podcast sticks to a color palette (white, blue, orange). It does not look like a transcript can be obtained. Links to social media and podcast sources are embedded. Some people who are involved in creating this are Terry O’Reilly, Sidney O’Reilly, Sidney O’Reilly, Allison Pinches, Callie O’Reilly, Debbie O’Reilly, Keith Ohman, Ian Lefeuvre, and Ari Posner.</Text></>,
  },
  {
    title: "In Plain Sight",
    img: MagnifyingGlass,
    description: <><Text>This episode follows the story of the escape of William and Ellen Craft and their love for each other. The writer gets the listener’s attention by talking about inhumane acts such as people selling slaves.</Text><NewLine></NewLine><Text>This podcast is structured like a story and an essay because there is a rising action, climax, and falling action as well as examples from the rhetoric triangle to document and explain the brutal treatment of slaves. The most exciting part of the story was when they were stopped when they were trying to board a boat.The storyteller built suspense by telling us the consequences of getting caught, and by telling us their previous close calls on the other parts of their journey.</Text><NewLine></NewLine><Text>The episode used the rhetoric triangle to keep the listener interested by sticking mostly towards pathos. Using mostly pathos allows the writer to both raise suspense and tell the audience about the mistreatment of slaves.</Text><NewLine></NewLine><Text>I think these storytellers are applauded for their craft because in this episode, they managed to tell an engaging story to capture the audience’s attention while simultaneously mixing in examples of mistreatment to show the cruel treatment of slaves.</Text><NewLine></NewLine><Text>Music is used during this podcast. In the background, there is a relaxing, mysterious song that would normally be present in detective stories during some parts of the podcast. This allows the listener to feel more relaxed and interested in analyzing the lives of William and Ellen like a detective. Additionally, the detective-like music is also thematically relevant to the title of the podcast - “In Plain Sight”.</Text><NewLine></NewLine><Text>On the podcast website, the podcast is presented with a theme of black and white; which can be seen in the title, pictures, text, and links. The transcript of the podcast can be obtained via email. The authors can be found on their about page.</Text></>
  }
]
